### PR TITLE
Upgrade both syntax to 3 and reason-react

### PR DESCRIPTION
**Pull request by imamatory**

### CODE REVIEW

**Comment by rickyvetter** [comment]
Thanks, this looks great!

**Comment by quicksnap** [comment]
Thanks @imamatory!

**Comment by imamatory** [comment]
@rickyvetter i'm gonna use this lib in production so it would be nice if you release version and publish to npm. There is breaking changes in reason-react so it should me minor. Thanks)

**Comment by rickyvetter** [comment]
@imamatory 0.2.0 is live now!!

**Comment by imamatory** [comment]
@rickyvetter thank you so much! 👍

**Pull request merged**
